## Assignment 6 — NumPy-II



## Q1.

In [ ]:
import numpy as np

temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])

# a.
corrected_temperature = temperature + 2
print("Corrected temperatures:", corrected_temperature)

# b.
fahrenheit = (9/5) * corrected_temperature + 32
print("Temperature in Fahrenheit:", fahrenheit)

# c.
greater_than_32 = corrected_temperature[corrected_temperature > 32]
print("Readings greater than 32°C:", greater_than_32)

# d.
count = np.sum(corrected_temperature > 32)
print("Number of readings exceeding 32°C:", count)

# e.
print("\nVectorization performs operations on the entire array at once.")
print("Boolean indexing selects values that satisfy a condition.")
print("Both approaches are generally more efficient than explicitly")
print("iterating through every value with a for loop.")


Corrected temperatures: [27 30 33 37 40 29 35 42]
Temperature in Fahrenheit: [ 80.6  86.   91.4  98.6 104.   84.2  95.  107.6]
Readings greater than 32°C: [33 37 40 35 42]
Number of readings exceeding 32°C: 5

Vectorization performs operations on the entire array at once.
Boolean indexing selects values that satisfy a condition.
Both approaches are generally more efficient than explicitly
iterating through every value with a for loop.


## Q2.

In [ ]:
steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])

# a.
total_steps = np.sum(steps)
print("Total steps:", total_steps)

# b.
mean_steps = np.mean(steps)
print("Mean steps:", mean_steps)

# c.
maximum = np.max(steps)
minimum = np.min(steps)
print("Maximum steps:", maximum)
print("Minimum steps:", minimum)

# d.
daily_total = np.sum(steps, axis=0)
print("Total steps for each day:", daily_total)

# e.
user_total = np.sum(steps, axis=1)
print("Total steps for each user:", user_total)

# f.
max_position = np.unravel_index(np.argmax(steps), steps.shape)
print("Position of maximum steps (row, column):", max_position)


Total steps: 84200
Mean steps: 7016.666666666667
Maximum steps: 9500
Minimum steps: 4500
Total steps for each day: [26500 27300 30400]
Total steps for each user: [18300 24500 14400 27000]
Position of maximum steps (row, column): (np.int64(3), np.int64(2))


## Q3. NumPy Slicing, Copying and Reshaping

In [ ]:
# a.
original = np.array([1, 2, 3, 4, 5, 6])
print("Original:", original)

# b.
subset = original[1:5]
print("Subset:", subset)

# c.
subset[0] = 999

print("\nAfter modifying subset:")
print("Original:", original)
print("Subset:", subset)

# d.
copied = original[1:5].copy()
copied[0] = 500

print("\nAfter modifying copied array:")
print("Original:", original)
print("Copied:", copied)

# e.
matrix = np.arange(1, 13).reshape(3, 4)

print("\n3 × 4 Matrix:")
print(matrix)

# f.

print("\nFirst row:")
print(matrix[0])

print("\nLast row:")
print(matrix[-1])

print("\nSecond column:")
print(matrix[:, 1])

print("\nElements from rows 1–2 and columns 2–3:")
print(matrix[1:3, 2:4])

# g.
flat_array = matrix.flatten()
ravel_array = matrix.ravel()

print("\nFlatten:")
print(flat_array)

print("\nRavel:")
print(ravel_array)

# h.
ravel_array[0] = 1000

print("\nAfter modifying ravel:")
print("Ravel array:", ravel_array)
print("Original matrix:")
print(matrix)

# i.
flat_array[1] = 2000

print("\nAfter modifying flatten:")
print("Flatten array:", flat_array)
print("Original matrix:")
print(matrix)

# j.
print("\nShape:", matrix.shape)
print("Dimensions (ndim):", matrix.ndim)
print("Size:", matrix.size)
print("Data type (dtype):", matrix.dtype)


Original: [1 2 3 4 5 6]
Subset: [2 3 4 5]

After modifying subset:
Original: [  1 999   3   4   5   6]
Subset: [999   3   4   5]

After modifying copied array:
Original: [  1 999   3   4   5   6]
Copied: [500   3   4   5]

3 × 4 Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

First row:
[1 2 3 4]

Last row:
[ 9 10 11 12]

Second column:
[ 2  6 10]

Elements from rows 1–2 and columns 2–3:
[[ 7  8]
 [11 12]]

Flatten:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Ravel:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

After modifying ravel:
Ravel array: [1000    2    3    4    5    6    7    8    9   10   11   12]
Original matrix:
[[1000    2    3    4]
 [   5    6    7    8]
 [   9   10   11   12]]

After modifying flatten:
Flatten array: [   1 2000    3    4    5    6    7    8    9   10   11   12]
Original matrix:
[[1000    2    3    4]
 [   5    6    7    8]
 [   9   10   11   12]]

Shape: (3, 4)
Dimensions (ndim): 2
Size: 12
Data type (dtype): int64


## Q4.

In [ ]:

X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
])

y = np.array([40, 65, 30, 85])

# a.
print("Shape of X:", X.shape)
print("Dimensions of X:", X.ndim)

# b.
XT = X.T
print("\nX.T:")
print(XT)

print("\nThe transpose represents features as rows and users as columns.")

# c.
XTX = XT @ X
print("\nX.T @ X:")
print(XTX)

# d.
XTX_inverse = np.linalg.inv(XTX)
print("\nInverse of X.T @ X:")
print(XTX_inverse)

# e.
beta = XTX_inverse @ XT @ y
print("\nOLS Coefficients:")
print(beta)

# f.
print("\nCoefficient interpretation:")
print("Coefficient 1 represents the effect of Sleep Hours.")
print("Coefficient 2 represents the effect of Activity Level.")
print("Coefficient 3 represents the effect of Stress Level.")

# g.
new_user = np.array([5, 40, 7])
predicted_score = new_user @ beta

print("\nNew user:", new_user)
print("Predicted Assistance Score:", predicted_score)


Shape of X: (4, 3)
Dimensions of X: 2

X.T:
[[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]

The transpose represents features as rows and users as columns.

X.T @ X:
[[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]

Inverse of X.T @ X:
[[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]

OLS Coefficients:
[-0.15921454  0.14083853 10.06302242]

Coefficient interpretation:
Coefficient 1 represents the effect of Sleep Hours.
Coefficient 2 represents the effect of Activity Level.
Coefficient 3 represents the effect of Stress Level.

New user: [ 5 40  7]
Predicted Assistance Score: 75.27862544779117
